services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wolofsign
      POSTGRES_USER: wolofuser
      POSTGRES_PASSWORD: wolof@123
      POSTGRES_HOST_AUTH_METHOD: trust
    command: postgres -c ssl=off
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD:-altoppe_redis_password}
    volumes:
      - redis_data:/data
    restart: unless-stopped

  web:
    user: root
    build: .
    environment:
      - DEBUG=False
      - SECRET_KEY=votre-secret-key-tres-longue-ici
      - DB_NAME=wolofsign
      - DB_USER=wolofuser
      - DB_PASSWORD=wolof@123
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_URL=redis://:wolofsign_redis_password@redis:6379/0
      - ALLOWED_HOSTS=sign.altoppe.sn,localhost,127.0.0.1
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro

    depends_on:
      - web
    restart: unless-stopped

# ⭐⭐ AJOUTEZ CETTE SECTION VOLUMES ⭐⭐
volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
